---
title: "MTH6139 Time Series" 
subtitle: "Coursework 1" 
author: "Azhar Numan" 
date: "Spring term 2026" 

#Since I used prophet, you will need to install it by using the command install.packages("prophet")

library(prophet)

#The purpose of this project is to look at co2 data from the past, and predict future levels of co2 using a time series.

data("co2")
#The co2 dataset has co2 measurements for every month between 01/01/1959 to 01/12/1997.

df<-data.frame(
    ds = seq(as.Date("1959-01-01"), as.Date("1997-12-01"), by="month"),
    y = as.numeric(co2)
)
#Here, ds represents the dates and y shows the co2 values. On a plot, they will represent the x and y axis respectively.

forecast_model <- prophet(df, yearly.seasonality = TRUE)
future <- make_future_dataframe(forecast_model, periods = 120, freq = 'month')
#This makes future dates to use for predictions. Since the period is 120 months, it translates to 10 years into the future. i.e 1/12/2007.

tail(future)
#This shows the dates of the last 5 months of the future 10 years.

forecast <- predict(forecast_model, future)
#This predicts values for the future dates.

tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])
#This shows the last 5 months of the predicted values of yhat, the lower and the upper bound of yhat.

plot(forecast_model, forecast)
#This plots the data, including the predicted values. It shows that as time has gone on, co2 values have gradually risen over the years.

prophet_plot_components(forecast_model, forecast)
#This shows the trend per year, and also the yearly trend. From this, it is clear to see that as time has gone on, more co2 has been emitted. This explains why in the prediction, co2 was shown to increase. The second plot shows the daily average co2 levels, compared to the yearly average. We can see that it peaks at around spring time and is at its lowest during autumn.